### ISSUE TITLE
set configuration without command line!

### ISSUE THREAD

**Issue by pws2016** [daycry/zoom#1]
Hello,
How i can replace the line command of configuration "> php spark zoom:publish" manually?
because i haven't command in my server!
thanks

**Comment by daycry** [comment]
Hi,

You can copy this file in app/Config.

<?php namespace Config;

use CodeIgniter\Config\BaseConfig;

class Zoom extends \Daycry\Zoom\Config\Zoom
{
    public $clientId = null;

    public $clientSecret = null;

    public $redirectUrl = null;
}

**Comment by pws2016** [comment]
I cretae the Zoom.php in config folder
but when i use $zoom = new \Daycry\Zoom\Zoom(); i get the error:
`Class 'League\OAuth2\Client\Provider\GenericProvider' not found`

How i can fix this?
i install ypur script manually so i just copy folder to app/ThirdParty/

**Comment by daycry** [comment]
Hi,
In which line? File?

try to install via composer "league/oauth2-client": "^2.4"

**Comment by daycry** [comment]
Or download this package and do manual installation like Zoom Package.

Thank you

**Comment by pws2016** [comment]
in which path i put the folder manually?

**Comment by pws2016** [comment]
i see you have set full CI folders but not have the Zoom script..
so please update it and set all necessary folders/files so i can use it as it directly..
thanks

**Comment by daycry** [comment]
Hi,

You can download from Github the code, and follow the instructions.(manual
installation)

This is the link for thelague oauthclient:
https://github.com/thephpleague/oauth2-client. If you download this code,
you can follow the manual instructions changing the route of this code.

Example:

$psr4 = [
    'Config'      => APPPATH . 'Config',
    APP_NAMESPACE => APPPATH,
    'App'         => APPPATH,
    'Daycry\Zoom' => APPPATH .'ThirdParty/zoom/src',

    'League\OAuth2\Client' => APPPATH .'ThirdParty/oauth2-client-master/src'

];


Thanks

**Comment by pws2016** [comment]
ok thanks i will try it again
